# Generated by Django 3.0 on 2020-10-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_img',
            field=models.CharField(default='N/a', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.CharField(default='N/a', max_length=500),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img_2',
            field=models.CharField(default='N/a', max_length=500),
        ),
        migrations.AlterField(
            model_name='properties',
            name='house',
            field=models.CharField(default='N/a', max_length=500),
        ),
    ]
