# Generated by Django 3.0 on 2020-10-19 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_auto_20201018_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='category',
            field=models.CharField(choices=[('RES', 'Residences'), ('OFF', 'Office'), ('COM', 'Commercial'), ('BUL', 'Building'), ('STO', 'STORAGE')], default='Residences', max_length=100),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=500)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='estate.Blog')),
            ],
        ),
    ]
