# Generated by Django 3.0 on 2020-10-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_auto_20201019_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='purpose',
            field=models.CharField(choices=[('Sale', 'sale'), ('rent', 'rent'), ('buy', 'buy')], default='buy', max_length=5),
        ),
    ]
